"""The route from a dataset page to the data, for a person and for an agent.

Twenty datasets have a route because a reviewer wrote one. Every other record carried a
single sentence naming the kind of door - "direct download, no account required",
"controlled through dbGaP" - which tells a reader what they are up against and not one
thing about what to do next. A researcher who has decided a dataset fits should not then
have to go and find out how a repository works.

So the route is derived here from what the repository has already told us: the access
tier, the components it called open or controlled, and the dataset's own identifiers. A
generated route is repository policy applied to one dataset, never an assertion about
that dataset, and it says so: every step carries DERIVED evidence pointing at the policy
page it came from. Reviewer-written routes are left exactly as they are.

Two audiences, because they take different doors to the same files. A person clicks
through a portal and signs an agreement; an agent calls an API, and the thing it most
needs to know is which calls quietly return a subset rather than an error when it has no
credentials.
"""

from __future__ import annotations

from datetime import UTC, datetime

from cds.model import (
    AccessAudience,
    AccessStep,
    Confidence,
    DatasetRecord,
    Evidence,
    Method,
)

# Documentation that states the policy each derived step applies. Checked by `cds verify`
# along with every other link on a page, so a repository reorganising its site shows up
# as a broken link rather than as confident wrong advice.
GDC_TRANSFER_TOOL = "https://gdc.cancer.gov/access-data/gdc-data-transfer-tool"
GDC_CONTROLLED = "https://gdc.cancer.gov/access-data/obtaining-access-controlled-data"
GDC_API = "https://docs.gdc.cancer.gov/API/Users_Guide/Getting_Started/"
PDC_TERMS = "https://pdc.cancer.gov/pdc/data-use-guidelines"
PDC_API = "https://pdc.cancer.gov/data-dictionary/publicapi-documentation/"
IDC_INDEX = "https://github.com/ImagingDataCommons/idc-index"
IDC_DOCS = "https://learn.canceridc.dev/"
TCIA_POLICY = "https://www.cancerimagingarchive.net/data-usage-policies-and-restrictions/"
CBIO_DATASETS = "https://www.cbioportal.org/datasets"
CBIO_DATAHUB = "https://github.com/cBioPortal/datahub"
CBIO_API = "https://docs.cbioportal.org/web-api-and-clients/"
HTAN_ACCESS = "https://humantumoratlas.org/data-access"
SYNAPSE_START = "https://help.synapse.org/docs/Getting-Started.2055471150.html"


def _evidence(url: str, label: str) -> Evidence:
    return Evidence(
        method=Method.DERIVED,
        source_url=url,
        source_label=label,
        retrieved_at=datetime.now(UTC),
        confidence=Confidence.MEDIUM,
        note=(
            "Generated by applying the repository's documented access policy to this "
            "dataset's identifiers. It is not a reviewer's account of this dataset, and "
            "a reviewed route replaces it where one exists."
        ),
    )


def is_derived(step: AccessStep) -> bool:
    """A step this module wrote, rather than one a reviewer wrote."""
    return any(e.method == Method.DERIVED for e in step.evidence)


def _ids(rec: DatasetRecord, scheme: str) -> list[str]:
    seen: list[str] = []
    for ident in rec.identifiers:
        if ident.scheme == scheme and ident.value not in seen:
            seen.append(ident.value)
    return seen


def _first(values: list[str]) -> str | None:
    return values[0] if values else None


def _component(parts: list[str]) -> str | None:
    return parts[0] if parts else None


# --------------------------------------------------------------------------------------
# one builder per repository
# --------------------------------------------------------------------------------------


def _gdc(rec: DatasetRecord) -> list[tuple[str, AccessStep]]:
    project = _first(_ids(rec, "gdc_project_id"))
    if not project:
        return []
    phs = _first(_ids(rec, "dbgap_phs"))
    phs_url = next((i.url for i in rec.identifiers if i.scheme == "dbgap_phs" and i.url), None)
    n_open = _component(rec.access.open_components)
    n_ctrl = _component(rec.access.controlled_components)
    label = "GDC access documentation"
    out: list[tuple[str, AccessStep]] = []

    out.append(
        (
            label,
            AccessStep(
                order=0,
                action="Open the project in the GDC Data Portal",
                detail=(
                    "The portal is the authority on how many cases and files this "
                    "project currently holds. Check those counts against the ones on "
                    "this page before requesting anything."
                ),
                url=rec.landing_page_url,
                est_time="5 minutes",
            ),
        )
    )
    if n_open:
        out.append(
            (
                label,
                AccessStep(
                    order=0,
                    action="Download the open files without an account",
                    detail=(
                        f"{n_open} are open access: no login, no request. Add them to "
                        "the portal cart to get a manifest, then fetch it with the GDC "
                        "Data Transfer Tool."
                    ),
                    url=GDC_TRANSFER_TOOL,
                    est_time="minutes to hours, by cohort size",
                    cli_snippet="gdc-client download -m gdc_manifest.txt",
                ),
            )
        )
    if n_ctrl:
        out.append(
            (
                label,
                AccessStep(
                    order=0,
                    action="Request controlled access through dbGaP",
                    detail=(
                        f"{n_ctrl} hold sequence-level data and are released only under "
                        "an approved data access request"
                        + (f" for {phs}." if phs else ".")
                        + " The request starts at dbGaP, not in the portal, and it is "
                        "your institution's signing official who submits it."
                    ),
                    url=GDC_CONTROLLED,
                    requires=(
                        ["eRA Commons account", "institutional signing official approval"]
                        + ([f"dbGaP data access request for {phs}"] if phs else [])
                    ),
                    est_time=rec.access.typical_turnaround or "days to a few weeks",
                ),
            )
        )
        out.append(
            (
                label,
                AccessStep(
                    order=0,
                    action="Download controlled files with your token",
                    detail=(
                        "An approved request yields a token that expires monthly. The "
                        "same manifest fetches nothing without it."
                    ),
                    url=phs_url or GDC_CONTROLLED,
                    requires=["approved dbGaP request", "GDC authentication token"],
                    cli_snippet=("gdc-client download -m gdc_manifest.txt -t gdc-user-token.txt"),
                ),
            )
        )
    out.append(
        (
            label,
            AccessStep(
                order=0,
                action="Query the project from code, with no credentials",
                detail=(
                    "The file index is public even where the files are not, so an agent "
                    "can size a cohort before anyone requests access."
                ),
                url=GDC_API,
                audience=AccessAudience.AGENT,
                cli_snippet=(
                    "curl -s 'https://api.gdc.cancer.gov/files' --get \\\n"
                    '  --data-urlencode \'filters={"op":"and","content":['
                    '{"op":"in","content":{"field":"cases.project.project_id",'
                    f'"value":["{project}"]}}}},'
                    '{"op":"in","content":{"field":"access","value":["open"]}}]}\' \\\n'
                    "  --data-urlencode 'fields=file_id,file_name,data_type' \\\n"
                    "  --data-urlencode 'size=10000' \\\n"
                    "  --data-urlencode 'format=TSV' > files.tsv"
                ),
            ),
        )
    )
    if n_ctrl:
        out.append(
            (
                label,
                AccessStep(
                    order=0,
                    action="Pass the token when the agent needs controlled files",
                    detail=(
                        "Without a token the same endpoints return the open subset and "
                        "HTTP 200. An agent that treats a short result as the whole "
                        "cohort will silently under-count; filter on access and compare "
                        "against the counts on this page."
                    ),
                    url=GDC_API,
                    audience=AccessAudience.AGENT,
                    requires=["GDC authentication token"],
                    cli_snippet=(
                        'curl -H "X-Auth-Token: $GDC_TOKEN" \\\n'
                        "  'https://api.gdc.cancer.gov/data/<file_id>' -o file.bam"
                    ),
                ),
            )
        )
    return out


def _pdc(rec: DatasetRecord) -> list[tuple[str, AccessStep]]:
    studies = _ids(rec, "pdc_study_id")
    study = _first(studies)
    if not study:
        return []
    label = "PDC data use guidelines"
    spans = (
        f" This cohort spans {len(studies)} PDC studies ({', '.join(studies)}); repeat for each."
        if len(studies) > 1
        else ""
    )
    return [
        (
            label,
            AccessStep(
                order=0,
                action="Open the study in the PDC portal",
                detail=(
                    "Proteomic data are released open: no account, no request, no waiting." + spans
                ),
                url=rec.landing_page_url,
                est_time="5 minutes",
            ),
        ),
        (
            label,
            AccessStep(
                order=0,
                action="Accept the data use guidelines and download",
                detail=(
                    "The portal asks you to accept the guidelines at download time. "
                    "They ask for citation and acknowledgement, not for approval."
                ),
                url=PDC_TERMS,
                est_time="minutes to hours, by study size",
            ),
        ),
        (
            label,
            AccessStep(
                order=0,
                action="Resolve the study UUID, then fetch the file manifest",
                detail=(
                    f"filesPerStudy keys on the version UUID, not on {study}. Passing "
                    "the PDC study id returns one row per file with every field null - "
                    "a successful call that looks like a study whose files carry no "
                    "metadata. Resolve the latest version through studyCatalog first. "
                    "acceptDUA: true is the programmatic form of the portal's terms "
                    "click; without it there are no signed download URLs."
                ),
                url=PDC_API,
                audience=AccessAudience.AGENT,
                cli_snippet=(
                    "python3 - <<'PY'\n"
                    "import requests\n"
                    f'STUDY = "{study}"\n'
                    'GQL = "https://pdc.cancer.gov/graphql"\n'
                    'catalog = requests.post(GQL, json={"query": "{ studyCatalog'
                    "(acceptDUA: true) { pdc_study_id versions { study_id "
                    'is_latest_version } } }"}).json()["data"]["studyCatalog"]\n'
                    'uuid = next(v["study_id"] for s in catalog '
                    'if s["pdc_study_id"] == STUDY\n'
                    '            for v in s["versions"] '
                    'if v["is_latest_version"] == "yes")\n'
                    'q = \'{ filesPerStudy(study_id: "%s" acceptDUA: true) '
                    "{ file_id file_name file_type data_category } }' % uuid\n"
                    'files = requests.post(GQL, json={"query": q})'
                    '.json()["data"]["filesPerStudy"]\n'
                    'print(len(files), "files")\n'
                    "PY"
                ),
            ),
        ),
    ]


def _idc(rec: DatasetRecord) -> list[tuple[str, AccessStep]]:
    coll = _first(_ids(rec, "idc_collection_id"))
    if not coll:
        return []
    label = "IDC and TCIA data usage policy"
    return [
        (
            label,
            AccessStep(
                order=0,
                action="Open the collection in the IDC portal",
                detail=(
                    "Imaging is public and stays in DICOM. Browse the series before "
                    "downloading; collections run to terabytes."
                ),
                url=rec.landing_page_url,
                est_time="5 minutes",
            ),
        ),
        (
            label,
            AccessStep(
                order=0,
                action="Read the collection's own licence",
                detail=(
                    (rec.access.license or "Per-collection licence")
                    + ". IDC licences differ by collection, and a non-commercial clause "
                    "on one collection does not travel to the next."
                ),
                url=TCIA_POLICY,
                est_time="5 minutes",
            ),
        ),
        (
            label,
            AccessStep(
                order=0,
                action="Download with idc-index",
                detail=(
                    "The package resolves the collection to its buckets and pulls them "
                    "with s5cmd. No account, no cloud project."
                ),
                url=IDC_INDEX,
                est_time="hours for a full collection",
                cli_snippet=(
                    "pip install idc-index\n"
                    'python -c "from idc_index import IDCClient; '
                    f"IDCClient().download_from_selection(collection_id='{coll}', "
                    "downloadDir='.')\""
                ),
            ),
        ),
        (
            label,
            AccessStep(
                order=0,
                action="List the series before pulling any pixels",
                detail=(
                    "One row per DICOM series, with modality and size, so an agent can "
                    "decide what to fetch instead of fetching everything."
                ),
                url=IDC_DOCS,
                audience=AccessAudience.AGENT,
                cli_snippet=(
                    'python -c "from idc_index import IDCClient; '
                    f"df = IDCClient().get_series(collection_id='{coll}'); "
                    "print(len(df), df['Modality'].value_counts().to_dict())\""
                ),
            ),
        ),
    ]


def _cbioportal(rec: DatasetRecord) -> list[tuple[str, AccessStep]]:
    study = _first(_ids(rec, "cbioportal_study_id"))
    if not study:
        return []
    label = "cBioPortal download documentation"
    return [
        (
            label,
            AccessStep(
                order=0,
                action="Open the study in cBioPortal",
                detail=(
                    "Harmonized mutation, copy-number, expression and clinical files, "
                    "open to anyone. "
                    + (
                        rec.access.citation_requirement
                        or "Cite the original study, not only the portal."
                    )
                ),
                url=rec.landing_page_url,
                est_time="5 minutes",
            ),
        ),
        (
            label,
            AccessStep(
                order=0,
                action="Download the whole study as a zip",
                detail=(
                    "The datasets page carries one zip per study: the same staging "
                    "files the portal itself loads. The datahub S3 bucket that older "
                    "guides quote is no longer readable anonymously."
                ),
                url=CBIO_DATASETS,
                est_time="minutes",
            ),
        ),
        (
            label,
            AccessStep(
                order=0,
                action="Or pull the staging files with git-lfs",
                detail=(
                    "Useful when you want one study out of a version-controlled copy. "
                    "Study folders are named by study id under public/."
                ),
                url=CBIO_DATAHUB,
                cli_snippet=(
                    "git lfs install --skip-repo --skip-smudge\n"
                    "git clone https://github.com/cBioPortal/datahub.git && cd datahub\n"
                    "git lfs install --local --skip-smudge\n"
                    f'git -c lfs.fetchexclude="" lfs pull -I public/{study}'
                ),
            ),
        ),
        (
            label,
            AccessStep(
                order=0,
                action="Read the study straight off the REST API",
                detail=(
                    "No key and no account; the API is rate-limited per address, so an "
                    "agent sweeping many studies should pace itself."
                ),
                url=CBIO_API,
                audience=AccessAudience.AGENT,
                cli_snippet=(
                    f"curl -s 'https://www.cbioportal.org/api/studies/{study}"
                    "/clinical-data?clinicalDataType=PATIENT&projection=SUMMARY'"
                ),
            ),
        ),
    ]


def _htan(rec: DatasetRecord) -> list[tuple[str, AccessStep]]:
    syn = _ids(rec, "synapse_id")
    label = "HTAN data access policy"
    out = [
        (
            label,
            AccessStep(
                order=0,
                action="Register at Synapse and accept the HTAN terms",
                detail=(
                    "One free account covers the whole atlas. The terms are "
                    "click-through; they are not a data access request."
                ),
                url=HTAN_ACCESS,
                requires=["Synapse account"],
                est_time="15 minutes",
            ),
        ),
        (
            label,
            AccessStep(
                order=0,
                action="Download the level 3-4 files from Synapse",
                detail=(
                    "Derived data and most imaging come down directly once the terms are accepted."
                ),
                url=SYNAPSE_START,
                est_time="minutes to hours",
                cli_snippet=(f"synapse get {syn[0]}" if syn else "synapse get <synapse id>"),
            ),
        ),
        (
            label,
            AccessStep(
                order=0,
                action="Request level 1-2 sequencing through dbGaP",
                detail=(
                    "Raw and aligned sequencing is controlled, on the same footing as "
                    "any other genomic data. Derived analyses rarely need it."
                ),
                url=HTAN_ACCESS,
                requires=["eRA Commons account", "approved dbGaP request"],
                est_time="days to a few weeks",
            ),
        ),
        (
            label,
            AccessStep(
                order=0,
                action="Give the agent a Synapse token, not a password",
                detail=(
                    "Unauthenticated calls return metadata and nothing to download, so "
                    "an agent reports an empty atlas rather than a permission error."
                ),
                url=SYNAPSE_START,
                audience=AccessAudience.AGENT,
                requires=["SYNAPSE_AUTH_TOKEN"],
                cli_snippet=(
                    "export SYNAPSE_AUTH_TOKEN=...\n"
                    'python -c "import synapseclient; syn = synapseclient.login(); '
                    + (
                        f"print(syn.get('{syn[0]}', downloadFile=False).name)\""
                        if syn
                        else "print(syn.getUserProfile()['userName'])\""
                    )
                ),
            ),
        ),
    ]
    return out


BUILDERS = {
    "GDC": _gdc,
    "PDC": _pdc,
    "IDC": _idc,
    "cBioPortal": _cbioportal,
    "HTAN": _htan,
}


def derive(rec: DatasetRecord) -> list[AccessStep]:
    """The route for one record, human steps first, numbered from one."""
    short = rec.repository.short_name if rec.repository else None
    builder = BUILDERS.get(short or "")
    if builder is None:
        return []
    built = builder(rec)
    human = [(lbl, s) for lbl, s in built if s.audience == AccessAudience.HUMAN]
    agent = [(lbl, s) for lbl, s in built if s.audience == AccessAudience.AGENT]
    out: list[AccessStep] = []
    for i, (lbl, step) in enumerate(human + agent, start=1):
        step.order = i
        step.evidence = [_evidence(step.url or "", lbl)] if step.url else [_evidence("", lbl)]
        out.append(step)
    return out


def apply_all(records: list[DatasetRecord]) -> dict[str, int]:
    """Fill in a route wherever no reviewer wrote one.

    A reviewed route is kept whole. Reviewers wrote those routes for a person, though, so
    where one carries nothing for an agent the derived machine steps are appended after
    it: the reviewer's judgement about the human route is not evidence that no API exists.
    """
    stats = {
        "n_derived": 0,
        "n_kept_curated": 0,
        "n_curated_given_machine_steps": 0,
        "n_no_builder": 0,
        "n_steps": 0,
    }
    for rec in records:
        curated = [s for s in rec.access_steps if not is_derived(s)]
        if curated:
            stats["n_kept_curated"] += 1
            if not any(s.audience == AccessAudience.AGENT for s in curated):
                machine = [s for s in derive(rec) if s.audience == AccessAudience.AGENT]
                for i, step in enumerate(machine, start=len(curated) + 1):
                    step.order = i
                rec.access_steps = curated + machine
                if machine:
                    stats["n_curated_given_machine_steps"] += 1
                    stats["n_steps"] += len(machine)
            else:
                rec.access_steps = curated
            continue
        steps = derive(rec)
        if not steps:
            stats["n_no_builder"] += 1
            continue
        rec.access_steps = steps
        stats["n_derived"] += 1
        stats["n_steps"] += len(steps)
    return stats
