"""Derive repository-specific routes from a dataset's identifiers and access tier.

Curated routes remain authoritative.  For records without one, this module adds a
short, policy-backed route for a person and an agent.  The generated steps describe
repository policy, not a new claim about the dataset, and carry derived evidence so the
site can distinguish them from expert-reviewed guidance.
"""

from __future__ import annotations

from datetime import UTC, datetime

from cds.model import AccessAudience, AccessStep, Confidence, DatasetRecord, Evidence, Method

GDC_TRANSFER_TOOL = "https://gdc.cancer.gov/access-data/gdc-data-transfer-tool"
GDC_CONTROLLED = "https://gdc.cancer.gov/access-data/obtaining-access-controlled-data"
GDC_API = "https://docs.gdc.cancer.gov/API/Users_Guide/Getting_Started/"
PDC_TERMS = "https://pdc.cancer.gov/pdc/data-use-guidelines"
PDC_API = "https://pdc.cancer.gov/data-dictionary/publicapi-documentation/"
IDC_INDEX = "https://github.com/ImagingDataCommons/idc-index"
IDC_DOCS = "https://learn.canceridc.dev/"
TCIA_POLICY = "https://www.cancerimagingarchive.net/data-usage-policies-and-restrictions/"
CBIO_DATASETS = "https://www.cbioportal.org/datasets"
CBIO_DATAHUB = "https://github.com/cBioPortal/datahub"
CBIO_API = "https://docs.cbioportal.org/web-api-and-clients/"
HTAN_ACCESS = "https://humantumoratlas.org/data-access"
SYNAPSE_START = "https://help.synapse.org/docs/Getting-Started.2055471150.html"

# ------------------------------------------------------------------------------------
# The snippets a reader copies.
#
# Written as whole templates with a `$ID` placeholder rather than assembled from
# concatenated fragments. Every one of these has to be legible enough that a reader can
# see what it does before running it - and the fragment form hid three real breakages:
# a curl filter one closing brace short, a GraphQL query keyed on the wrong identifier,
# and a call to a method the library does not have. Each is re-checked against the live
# API; `pipeline/tests/test_access_routes.py` pins the shapes that broke.
# ------------------------------------------------------------------------------------

GDC_LIST_FILES = """\
curl -s 'https://api.gdc.cancer.gov/files' --get \\
  --data-urlencode 'filters={"op":"in","content":{"field":"cases.project.project_id","value":["$ID"]}}' \\
  --data-urlencode 'fields=file_id,file_name,data_type' \\
  --data-urlencode 'size=10000' --data-urlencode 'format=TSV'"""

# filesPerStudy keys on the study UUID. Handed the pdc_study_id it returns the right
# number of rows with every column null, which looks like an empty study rather than a
# mistake, so the lookup has to come first.
PDC_LIST_FILES = """\
python - <<'PY'
import requests
API = "https://proteomic.datacommons.cancer.gov/graphql"

def gql(query, **variables):
    r = requests.post(API, json={"query": query, "variables": variables}, timeout=180)
    r.raise_for_status()
    body = r.json()
    if body.get("errors"):
        raise RuntimeError(body["errors"][0]["message"])
    return body["data"]

study = gql('query($id:String!){ study(pdc_study_id:$id acceptDUA:true){ study_id } }',
            id="$ID")["study"][0]
files = gql('query($sid:String!){ filesPerStudy(study_id:$sid acceptDUA:true)'
            '{ file_id file_name file_size } }', sid=study["study_id"])["filesPerStudy"]
print(len(files), "files")
PY"""

IDC_DOWNLOAD = """\
pip install idc-index
python - <<'PY'
from idc_index import IDCClient
IDCClient().download_from_selection(collection_id="$ID", downloadDir=".")
PY"""

# IDCClient has no get_series; the collection is filtered out of the index frame.
IDC_LIST_SERIES = """\
python - <<'PY'
from idc_index import IDCClient
i = IDCClient().index
s = i[i["collection_id"] == "$ID"]
print(len(s), "series", s["PatientID"].nunique(), "patients",
      round(s["series_size_MB"].sum() / 1024, 1), "GB")
print(s["Modality"].value_counts().to_dict())
PY"""

CBIO_DATAHUB_PULL = """\
git clone https://github.com/cBioPortal/datahub.git && cd datahub
git -c lfs.fetchexclude="" lfs pull -I public/$ID"""

CBIO_REST = (
    "curl -s 'https://www.cbioportal.org/api/studies/$ID"
    "/clinical-data?clinicalDataType=PATIENT&projection=SUMMARY'"
)


def _snippet(template: str, identifier: str) -> str:
    """Fill a snippet template. One placeholder, so no brace escaping to get wrong."""
    return template.replace("$ID", identifier)


def _evidence(url: str, label: str) -> Evidence:
    return Evidence(
        method=Method.DERIVED,
        source_url=url or None,
        source_label=label,
        retrieved_at=datetime.now(UTC),
        confidence=Confidence.MEDIUM,
        note=(
            "Generated by applying the repository's documented access policy to this "
            "dataset's identifiers. It is not a reviewer's account of this dataset."
        ),
    )


def is_derived(step: AccessStep) -> bool:
    return any(e.method == Method.DERIVED for e in step.evidence)


def _ids(rec: DatasetRecord, scheme: str) -> list[str]:
    return list(dict.fromkeys(i.value for i in rec.identifiers if i.scheme == scheme))


def _first(values: list[str]) -> str | None:
    return values[0] if values else None


def _step(
    action: str,
    *,
    detail: str,
    url: str,
    audience: AccessAudience = AccessAudience.HUMAN,
    requires: list[str] | None = None,
    est_time: str | None = None,
    cli_snippet: str | None = None,
) -> AccessStep:
    return AccessStep(
        order=0,
        action=action,
        detail=detail,
        url=url,
        audience=audience,
        requires=requires or [],
        est_time=est_time,
        cli_snippet=cli_snippet,
    )


def _gdc(rec: DatasetRecord) -> list[AccessStep]:
    project = _first(_ids(rec, "gdc_project_id"))
    if not project:
        return []
    steps = [
        _step(
            "Open the project in the GDC Data Portal",
            detail=(
                "Check the portal's current case and file counts before requesting "
                "anything; the cohort can change after this record was built."
            ),
            url=rec.landing_page_url or GDC_API,
            est_time="5 minutes",
        )
    ]
    if rec.access.open_components:
        steps.append(
            _step(
                "Download the open files without an account",
                detail=(
                    f"{rec.access.open_components[0]} are marked open access. Add them "
                    "to a portal cart, export a manifest, and fetch it with the GDC "
                    "Data Transfer Tool."
                ),
                url=GDC_TRANSFER_TOOL,
                est_time="minutes to hours, by cohort size",
                cli_snippet="gdc-client download -m gdc_manifest.txt",
            )
        )
    if rec.access.controlled_components:
        phs = _first(_ids(rec, "dbgap_phs"))
        phs_url = next((i.url for i in rec.identifiers if i.scheme == "dbgap_phs" and i.url), None)
        steps.extend(
            [
                _step(
                    "Request controlled access through dbGaP",
                    detail=(
                        f"{rec.access.controlled_components[0]} require an approved data "
                        "access request. The request starts at dbGaP, not in the portal."
                        + (f" The relevant study is {phs}." if phs else "")
                    ),
                    url=GDC_CONTROLLED,
                    requires=["eRA Commons account", "institutional signing official approval"]
                    + ([f"dbGaP data access request for {phs}"] if phs else []),
                    est_time=rec.access.typical_turnaround or "days to a few weeks",
                ),
                _step(
                    "Download controlled files with your token",
                    detail=(
                        "An approved request yields a token. The same manifest fetches "
                        "nothing controlled without it."
                    ),
                    url=phs_url or GDC_CONTROLLED,
                    requires=["approved dbGaP request", "GDC authentication token"],
                    cli_snippet="gdc-client download -m gdc_manifest.txt -t gdc-user-token.txt",
                ),
            ]
        )
    steps.append(
        _step(
            "Query the project from code, with no credentials",
            detail=(
                "The file index is public even where files are not, so an agent can "
                "size the cohort before anyone requests access."
            ),
            url=GDC_API,
            audience=AccessAudience.AGENT,
            cli_snippet=_snippet(GDC_LIST_FILES, project),
        )
    )
    if rec.access.controlled_components:
        steps.append(
            _step(
                "Pass the token when the agent needs controlled files",
                detail=(
                    "Without a token, an API query may return only the open subset. "
                    "Compare returned counts with the record before treating them as "
                    "the whole cohort."
                ),
                url=GDC_API,
                audience=AccessAudience.AGENT,
                requires=["GDC authentication token"],
                cli_snippet='curl -H "X-Auth-Token: $GDC_TOKEN" https://api.gdc.cancer.gov/data/<file_id>',
            )
        )
    return steps


def _pdc(rec: DatasetRecord) -> list[AccessStep]:
    studies = _ids(rec, "pdc_study_id")
    study = _first(studies)
    if not study:
        return []
    spans = (
        f" This record spans {len(studies)} PDC studies; repeat for each."
        if len(studies) > 1
        else ""
    )
    return [
        _step(
            "Open the study in the PDC portal",
            detail="Proteomic data are released open; the portal's use guidelines still apply."
            + spans,
            url=rec.landing_page_url or PDC_TERMS,
            est_time="5 minutes",
        ),
        _step(
            "Accept the data use guidelines and download",
            detail="The portal asks for acknowledgement and citation, not a data access request.",
            url=PDC_TERMS,
            est_time="minutes to hours, by study size",
        ),
        _step(
            "Resolve the study UUID, then fetch the file manifest",
            detail=(
                f"filesPerStudy keys on the study UUID, not on {study}: called with the "
                "pdc_study_id it returns the right number of rows with every column "
                "null. Resolve the UUID first and pass the terms acknowledgement."
            ),
            url=PDC_API,
            audience=AccessAudience.AGENT,
            cli_snippet=_snippet(PDC_LIST_FILES, study),
        ),
    ]


def _idc(rec: DatasetRecord) -> list[AccessStep]:
    collection = _first(_ids(rec, "idc_collection_id"))
    if not collection:
        return []
    return [
        _step(
            "Open the collection in the IDC portal",
            detail="Browse the series before downloading; imaging collections can be very large.",
            url=rec.landing_page_url or IDC_DOCS,
            est_time="5 minutes",
        ),
        _step(
            "Read the collection's own licence",
            detail=(
                (rec.access.license or "Per-collection licence")
                + ". IDC licences differ by collection."
            ),
            url=TCIA_POLICY,
            est_time="5 minutes",
        ),
        _step(
            "Download with idc-index",
            detail="The package resolves the collection to its buckets and pulls selected data.",
            url=IDC_INDEX,
            est_time="hours for a full collection",
            cli_snippet=_snippet(IDC_DOWNLOAD, collection),
        ),
        _step(
            "List the series before pulling pixels",
            detail="List modality and size first so an agent can choose what to fetch.",
            url=IDC_DOCS,
            audience=AccessAudience.AGENT,
            cli_snippet=_snippet(IDC_LIST_SERIES, collection),
        ),
    ]


def _cbioportal(rec: DatasetRecord) -> list[AccessStep]:
    study = _first(_ids(rec, "cbioportal_study_id"))
    if not study:
        return []
    return [
        _step(
            "Open the study in cBioPortal",
            detail=(
                "Harmonized molecular and clinical files are open. "
                + (
                    rec.access.citation_requirement
                    or "Cite the original study as well as the portal."
                )
            ),
            url=rec.landing_page_url or CBIO_DATASETS,
            est_time="5 minutes",
        ),
        _step(
            "Download the whole study as a zip",
            detail="The datasets page carries the staging files used by the portal.",
            url=CBIO_DATASETS,
            est_time="minutes",
        ),
        _step(
            "Or pull the staging files with git-lfs",
            detail="Study folders are named by study id under public/.",
            url=CBIO_DATAHUB,
            cli_snippet=_snippet(CBIO_DATAHUB_PULL, study),
        ),
        _step(
            "Read the study straight from the REST API",
            detail="No key is required; pace requests when sweeping many studies.",
            url=CBIO_API,
            audience=AccessAudience.AGENT,
            cli_snippet=_snippet(CBIO_REST, study),
        ),
    ]


def _htan(rec: DatasetRecord) -> list[AccessStep]:
    synapse = _first(_ids(rec, "synapse_id"))
    if not synapse:
        return []
    return [
        _step(
            "Register at Synapse and accept the HTAN terms",
            detail="One free account covers the atlas; the terms are click-through, not a data access request.",
            url=HTAN_ACCESS,
            requires=["Synapse account"],
            est_time="15 minutes",
        ),
        _step(
            "Download the available files from Synapse",
            detail="Derived data and other released files become available after the terms are accepted.",
            url=SYNAPSE_START,
            est_time="minutes to hours",
            cli_snippet=f"synapse get {synapse}",
        ),
        _step(
            "Request controlled sequencing through dbGaP when needed",
            detail="Raw and aligned sequencing may require an approved request; derived analyses often do not.",
            url=HTAN_ACCESS,
            requires=["eRA Commons account", "approved dbGaP request"],
            est_time="days to a few weeks",
        ),
        _step(
            "Give an agent a Synapse token, not a password",
            detail="Unauthenticated calls return metadata and no files, so an agent should report the credential requirement explicitly.",
            url=SYNAPSE_START,
            audience=AccessAudience.AGENT,
            requires=["SYNAPSE_AUTH_TOKEN"],
            cli_snippet="export SYNAPSE_AUTH_TOKEN=...\nsynapse get " + synapse,
        ),
    ]


BUILDERS = {
    "GDC": _gdc,
    "PDC": _pdc,
    "IDC": _idc,
    "cBioPortal": _cbioportal,
    "HTAN": _htan,
}


def derive(rec: DatasetRecord) -> list[AccessStep]:
    """Build a numbered route, with human steps before agent steps."""
    builder = BUILDERS.get(rec.repository.short_name if rec.repository else "")
    if builder is None:
        return []
    built = builder(rec)
    human = [s for s in built if s.audience == AccessAudience.HUMAN]
    agent = [s for s in built if s.audience == AccessAudience.AGENT]
    out: list[AccessStep] = []
    label = f"{rec.repository.short_name} access documentation"
    for order, step in enumerate(human + agent, start=1):
        step.order = order
        step.evidence = [_evidence(step.url or "", label)]
        out.append(step)
    return out


def apply_all(records: list[DatasetRecord]) -> dict[str, int]:
    """Fill missing routes and append machine steps to reviewed human routes."""
    stats = {
        "n_derived": 0,
        "n_kept_curated": 0,
        "n_curated_given_machine_steps": 0,
        "n_no_builder": 0,
        "n_steps": 0,
    }
    for rec in records:
        curated = [s for s in rec.access_steps if not is_derived(s)]
        if curated:
            stats["n_kept_curated"] += 1
            if not any(s.audience == AccessAudience.AGENT for s in curated):
                machine = [s for s in derive(rec) if s.audience == AccessAudience.AGENT]
                for order, step in enumerate(machine, start=len(curated) + 1):
                    step.order = order
                rec.access_steps = curated + machine
                if machine:
                    stats["n_curated_given_machine_steps"] += 1
                    stats["n_steps"] += len(machine)
            else:
                rec.access_steps = curated
            continue
        steps = derive(rec)
        if not steps:
            stats["n_no_builder"] += 1
            continue
        rec.access_steps = steps
        stats["n_derived"] += 1
        stats["n_steps"] += len(steps)
    return stats
