import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // `next dev` otherwise writes AGENTS.md and CLAUDE.md into this directory on every
  // start. Agent guidance for this repository lives at the repository root.
  agentRules: false,
  // The pipeline writes llms.txt and openapi.json into public/data with everything
  // else; both conventions expect them at the site root.
  async rewrites() {
    return [
      { source: "/llms.txt", destination: "/data/llms.txt" },
      { source: "/openapi.json", destination: "/data/openapi.json" },
    ];
  },
  // Dataset record JSON is generated by the pipeline and served as-is; it doubles as
  // the bulk agent API, so it must be cacheable and CORS-readable by other tools.
  async headers() {
    return [
      {
        source: "/data/:path*",
        headers: [
          { key: "Access-Control-Allow-Origin", value: "*" },
          { key: "Cache-Control", value: "public, max-age=3600, s-maxage=86400" },
        ],
      },
      {
        source: "/api/:path*",
        headers: [
          { key: "Access-Control-Allow-Origin", value: "*" },
          { key: "Access-Control-Allow-Methods", value: "GET, OPTIONS" },
        ],
      },
    ];
  },
};

export default nextConfig;
