import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // `next dev` otherwise writes AGENTS.md and CLAUDE.md into this directory on every
  // start. Agent guidance for this repository lives at the repository root.
  agentRules: false,
  // The pipeline writes llms.txt and openapi.json into public/data with everything
  // else; both conventions expect them at the site root.
  async rewrites() {
    return [
      { source: "/llms.txt", destination: "/data/llms.txt" },
      { source: "/openapi.json", destination: "/data/openapi.json" },
    ];
  },
  // Dataset record JSON is generated by the pipeline and served as-is; it doubles as
  // the bulk agent API, so it must be cacheable and CORS-readable by other tools.
  async headers() {
    return [
      {
        source: "/data/:path*",
        headers: [
          { key: "Access-Control-Allow-Origin", value: "*" },
          { key: "Cache-Control", value: "public, max-age=3600, s-maxage=86400" },
        ],
      },
      {
        source: "/api/:path*",
        headers: [
          { key: "Access-Control-Allow-Origin", value: "*" },
          { key: "Access-Control-Allow-Methods", value: "GET, OPTIONS" },
        ],
      },
      // The pages that have to be rendered per request, because the query string is
      // part of what they show. Nothing about them is per-visitor: the same URL renders
      // the same document for everyone until the corpus is rebuilt, so the shared cache
      // can answer for them and the function only runs on a miss. Without this every
      // visit to the browse page re-rendered six hundred rows in a serverless function.
      //
      // The agent endpoint is deliberately not here: its answer depends on a model and
      // it sets `no-store` itself.
      {
        source: "/:path(datasets|compare|network|ask)",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=0, s-maxage=3600, stale-while-revalidate=86400",
          },
        ],
      },
      {
        source: "/api/v1/search",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=0, s-maxage=3600, stale-while-revalidate=86400",
          },
        ],
      },
    ];
  },
};

export default nextConfig;
